/**
 * RepoWiki DB  (SQLite-backed persistence)  — the "Structure + Curate → RepoWiki DB" box.
 *
 * Persists the indexed codebase so it survives server restarts:
 *   - meta    : one row describing the currently-indexed codebase
 *   - files   : per-file language + line count
 *   - chunks  : every retrievable chunk WITH its embedding vector (stored as JSON)
 *   - wiki    : per-file curated summaries (generated by the RepoWiki service)
 *
 * On startup the server reloads `chunks` into the in-memory VectorStore, so search works
 * immediately without re-ingesting.
 *
 * NOTE: every method is async even though node:sqlite is synchronous — the Postgres store
 * (db/pgRepoWikiStore.js) implements the exact same interface, so callers never know which
 * driver is behind it.
 */
import { openDatabase } from './sqlite.js';

const SCHEMA = `
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);
CREATE TABLE IF NOT EXISTS files (
  rel_path   TEXT PRIMARY KEY,
  language   TEXT,
  line_count INTEGER
);
CREATE TABLE IF NOT EXISTS chunks (
  id         TEXT PRIMARY KEY,
  rel_path   TEXT,
  language   TEXT,
  start_line INTEGER,
  end_line   INTEGER,
  text       TEXT,
  vector     TEXT
);
CREATE INDEX IF NOT EXISTS idx_chunks_path ON chunks(rel_path);
CREATE TABLE IF NOT EXISTS wiki (
  rel_path   TEXT PRIMARY KEY,
  language   TEXT,
  summary    TEXT,
  symbols    TEXT,
  updated_at TEXT
);
`;

export class RepoWikiStore {
  constructor(db) {
    this.db = db;
  }

  /** Open the DB file and ensure the schema exists. */
  static async open(filePath) {
    const db = await openDatabase(filePath);
    db.exec(SCHEMA);
    return new RepoWikiStore(db);
  }

  /** Wipe all indexed data (called at the start of a fresh ingest). */
  async reset() {
    this.db.exec('DELETE FROM meta; DELETE FROM files; DELETE FROM chunks; DELETE FROM wiki;');
  }

  /** Close the underlying connection (graceful shutdown). */
  async close() {
    this.db.close();
  }

  // --- meta -----------------------------------------------------------------
  async saveMeta(meta) {
    const stmt = this.db.prepare('INSERT OR REPLACE INTO meta (key, value) VALUES (?, ?)');
    stmt.run('codebase', JSON.stringify(meta));
  }

  async getMeta() {
    const row = this.db.prepare('SELECT value FROM meta WHERE key = ?').get('codebase');
    return row ? JSON.parse(row.value) : null;
  }

  // --- files ----------------------------------------------------------------
  async insertFiles(files) {
    const stmt = this.db.prepare(
      'INSERT OR REPLACE INTO files (rel_path, language, line_count) VALUES (?, ?, ?)'
    );
    this.#tx(() => {
      for (const f of files) stmt.run(f.relPath, f.language, f.lineCount || 0);
    });
  }

  // --- chunks (with vectors) ------------------------------------------------
  async insertChunks(records) {
    const stmt = this.db.prepare(
      `INSERT OR REPLACE INTO chunks (id, rel_path, language, start_line, end_line, text, vector)
       VALUES (?, ?, ?, ?, ?, ?, ?)`
    );
    this.#tx(() => {
      for (const r of records) {
        stmt.run(
          r.id,
          r.metadata.relPath,
          r.metadata.language,
          r.metadata.startLine,
          r.metadata.endLine,
          r.metadata.text,
          JSON.stringify(r.vector)
        );
      }
    });
  }

  /** Return all chunks as VectorStore records: { id, vector, metadata }. */
  async allChunks() {
    const rows = this.db.prepare('SELECT * FROM chunks').all();
    return rows.map((row) => ({
      id: row.id,
      vector: JSON.parse(row.vector),
      metadata: {
        relPath: row.rel_path,
        language: row.language,
        startLine: row.start_line,
        endLine: row.end_line,
        text: row.text,
      },
    }));
  }

  // --- wiki -----------------------------------------------------------------
  async upsertWiki(entry) {
    const stmt = this.db.prepare(
      `INSERT OR REPLACE INTO wiki (rel_path, language, summary, symbols, updated_at)
       VALUES (?, ?, ?, ?, ?)`
    );
    stmt.run(
      entry.relPath,
      entry.language,
      entry.summary,
      JSON.stringify(entry.symbols || []),
      new Date().toISOString()
    );
  }

  async getWiki(relPath) {
    const row = this.db.prepare('SELECT * FROM wiki WHERE rel_path = ?').get(relPath);
    return row ? this.#wikiRow(row) : null;
  }

  async listWiki() {
    const rows = this.db.prepare('SELECT * FROM wiki ORDER BY rel_path').all();
    return rows.map((r) => this.#wikiRow(r));
  }

  #wikiRow(row) {
    return {
      relPath: row.rel_path,
      language: row.language,
      summary: row.summary,
      symbols: JSON.parse(row.symbols || '[]'),
      updatedAt: row.updated_at,
    };
  }

  // --- helpers --------------------------------------------------------------
  #tx(fn) {
    this.db.exec('BEGIN');
    try {
      fn();
      this.db.exec('COMMIT');
    } catch (err) {
      this.db.exec('ROLLBACK');
      throw err;
    }
  }
}

export default RepoWikiStore;
