/**
 * Mock LLM provider (placeholder).
 *
 * Implements the same interface a real LLM provider will: `async complete({ system, prompt })`.
 * Instead of calling a model, it produces a deterministic, readable answer by summarising the
 * retrieved context that the RAG engine passed in. This lets the end-to-end flow (and the frontend)
 * work today; swapping in a real model later changes only this file's sibling, not the callers.
 */

/**
 * @param {{ system?: string, prompt: string, context?: Array }} args
 * @returns {Promise<{ text: string, model: string }>}
 */
export async function complete({ prompt, context = [] }) {
  const question = extractQuestion(prompt);

  let text;
  if (context.length === 0) {
    text =
      `I couldn't find relevant code for: "${question}".\n` +
      `Make sure a codebase has been ingested via POST /api/ingest.`;
  } else {
    const fileList = [...new Set(context.map((c) => c.metadata.relPath))];
    const top = context[0];
    text =
      `Based on the indexed code, here is what relates to "${question}":\n\n` +
      `The most relevant location is ${top.metadata.relPath} ` +
      `(lines ${top.metadata.startLine}-${top.metadata.endLine}). ` +
      `In total ${context.length} relevant snippet(s) were found across ` +
      `${fileList.length} file(s): ${fileList.join(', ')}.\n\n` +
      `Top snippet preview:\n` +
      '```' + (top.metadata.language || '') + '\n' +
      truncate(top.metadata.text, 600) +
      '\n```\n\n' +
      `(This explanation was generated by the MOCK provider. Configure a real LLM provider to get ` +
      `a natural-language synthesis instead of a structured summary.)`;
  }

  return { text, model: 'mock-llm' };
}

function extractQuestion(prompt) {
  const m = prompt.match(/Question:\s*(.*)$/m);
  return m ? m[1].trim() : prompt.slice(0, 120);
}

function truncate(s, n) {
  return s.length > n ? `${s.slice(0, n)}…` : s;
}

export default { complete, name: 'mock' };
